#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AI 自动优化 - 一键删除冗余代码
安全、智能、自动化
"""

import os
import re
import sys
from pathlib import Path
from datetime import datetime


def delete_backup_files():
    """删除所有备份文件"""
    print("\n" + "="*60)
    print("🗑️  步骤 1: 删除备份文件")
    print("="*60)
    
    backup_patterns = ['*.backup', '*.bak', '*.old', '*~']
    deleted_count = 0
    saved_bytes = 0
    
    for pattern in backup_patterns:
        for file in Path('.').rglob(pattern):
            if '.venv' not in str(file) and 'node_modules' not in str(file):
                size = file.stat().st_size
                file.unlink()
                print(f"  ✓ 删除：{file} ({size:,} bytes)")
                deleted_count += 1
                saved_bytes += size
    
    print(f"\n✓ 共删除 {deleted_count} 个备份文件，释放 {saved_bytes:,} bytes")
    return deleted_count, saved_bytes


def remove_empty_html_tags(content):
    """删除空的 HTML 标签"""
    # 删除空的 div, span, p 标签（保留有 id 或 class 的）
    content = re.sub(
        r'<(div|span|p)(?![^>]*\b(id|class)\s*=\s*["\'][^"\']*["\'])[^>]*>\s*</\1>',
        '',
        content,
        flags=re.IGNORECASE
    )
    return content


def remove_duplicate_class_values(content):
    """删除重复的 class 值"""
    def deduplicate_class(match):
        classes = match.group(1).split()
        unique_classes = list(dict.fromkeys(classes))  # 保持顺序去重
        return f'class="{" ".join(unique_classes)}"'
    
    content = re.sub(r'class="([^"]*)"', deduplicate_class, content)
    return content


def remove_useless_comments(content):
    """删除无用的注释"""
    # 删除作者、版权相关的注释
    content = re.sub(r'<!--\s*Author:\s*.*?-->', '', content, flags=re.IGNORECASE | re.DOTALL)
    content = re.sub(r'<!--\s*Copyright.*?-->', '', content, flags=re.IGNORECASE | re.DOTALL)
    content = re.sub(r'<!--\s*Created by.*?-->', '', content, flags=re.IGNORECASE | re.DOTALL)
    content = re.sub(r'<!--\s*Generated by.*?-->', '', content, flags=re.IGNORECASE | re.DOTALL)
    return content


def optimize_html_file(file_path):
    """优化单个 HTML 文件"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            original_content = f.read()
        
        original_size = len(original_content)
        
        # 应用所有优化
        optimized_content = original_content
        optimized_content = remove_empty_html_tags(optimized_content)
        optimized_content = remove_duplicate_class_values(optimized_content)
        optimized_content = remove_useless_comments(optimized_content)
        
        # 只有当内容确实改变时才写入
        if optimized_content != original_content:
            optimized_size = len(optimized_content)
            reduction = ((original_size - optimized_size) / original_size * 100) if original_size > 0 else 0
            
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(optimized_content)
            
            return True, original_size, optimized_size, reduction
        else:
            return False, 0, 0, 0
            
    except Exception as e:
        print(f"  ✗ 处理失败 {file_path}: {e}")
        return False, 0, 0, 0


def batch_optimize_html_files():
    """批量优化 HTML 文件"""
    print("\n" + "="*60)
    print("🎨 步骤 2: 批量优化 HTML 文件")
    print("="*60)
    
    html_files = []
    for file in Path('.').rglob('*.html'):
        if '.venv' not in str(file) and 'node_modules' not in str(file) and '.deploy_git' not in str(file):
            html_files.append(file)
    
    print(f"  发现 {len(html_files)} 个 HTML 文件\n")
    
    optimized_count = 0
    total_saved = 0
    
    for i, file in enumerate(html_files, 1):
        success, orig_size, opt_size, reduction = optimize_html_file(file)
        if success:
            optimized_count += 1
            saved = orig_size - opt_size
            total_saved += saved
            print(f"  [{i}/{len(html_files)}] ✓ {file.name}: 节省 {saved:,} bytes ({reduction:.2f}%)")
    
    print(f"\n✓ 共优化 {optimized_count}/{len(html_files)} 个文件")
    print(f"✓ 总计节省 {total_saved:,} bytes")
    
    return optimized_count, total_saved


def remove_unused_imports_in_python(file_path):
    """删除 Python 文件中未使用的导入"""
    if not str(file_path).endswith('.py'):
        return False, 0
    
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # 简单的检测逻辑
        import_pattern = r'^(?:from\s+(\S+)\s+)?import\s+(\w+)'
        imports = re.findall(import_pattern, content, re.MULTILINE)
        
        removed_imports = []
        new_lines = []
        
        for line in content.split('\n'):
            match = re.match(import_pattern, line)
            if match:
                module = match.group(2) if match.group(2) else match.group(1)
                # 检查是否在代码中使用（排除导入行本身）
                code_without_imports = re.sub(r'^.*import.*$', '', content, flags=re.MULTILINE)
                if module and module not in code_without_imports:
                    removed_imports.append(module)
                    continue  # 跳过这行
            new_lines.append(line)
        
        if removed_imports:
            new_content = '\n'.join(new_lines)
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(new_content)
            return True, len(removed_imports)
        
        return False, 0
        
    except Exception as e:
        print(f"  ✗ 处理失败 {file_path}: {e}")
        return False, 0


def batch_remove_unused_imports():
    """批量删除 Python 文件中的未使用导入"""
    print("\n" + "="*60)
    print("📦 步骤 3: 删除未使用的 Python 导入")
    print("="*60)
    
    py_files = []
    for file in Path('.').rglob('*.py'):
        if '.venv' not in str(file) and 'venv' not in str(file) and 'node_modules' not in str(file):
            py_files.append(file)
    
    print(f"  发现 {len(py_files)} 个 Python 文件\n")
    
    optimized_count = 0
    total_removed = 0
    
    for file in py_files:
        success, count = remove_unused_imports_in_python(file)
        if success:
            optimized_count += 1
            total_removed += count
            print(f"  ✓ {file.name}: 删除 {count} 个未使用的导入")
    
    print(f"\n✓ 共优化 {optimized_count} 个文件")
    print(f"✓ 总计删除 {total_removed} 个未使用的导入")
    
    return optimized_count, total_removed


def generate_final_report(stats):
    """生成最终报告"""
    report = []
    report.append("# AI 自动优化报告")
    report.append(f"执行时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
    
    report.append("## 📊 优化统计\n")
    report.append(f"- 删除备份文件：**{stats['backup_deleted']}** 个，释放 **{stats['backup_saved']:,}** bytes")
    report.append(f"- 优化 HTML 文件：**{stats['html_optimized']}** 个，节省 **{stats['html_saved']:,}** bytes")
    report.append(f"- 删除未使用导入：**{stats['imports_removed']}** 个\n")
    
    total_saved = stats['backup_saved'] + stats['html_saved']
    report.append(f"**总计节省空间**: {total_saved:,} bytes\n")
    
    report.append("## ✅ 已完成的优化\n")
    report.append("1. ✅ 删除所有备份文件（.backup, .bak, .old）")
    report.append("2. ✅ 清理空的 HTML 标签（div, span, p）")
    report.append("3. ✅ 删除重复的 class 属性值")
    report.append("4. ✅ 删除无用的注释（Author, Copyright 等）")
    report.append("5. ✅ 移除未使用的 Python 导入\n")
    
    report.append("## 💡 后续建议\n")
    report.append("1. 检查 `.gitignore` 确保备份文件不会被提交")
    report.append("2. 定期运行此脚本保持代码整洁")
    report.append("3. 考虑使用代码压缩工具进一步优化生产环境\n")
    
    report_content = '\n'.join(report)
    
    output_file = 'ai_optimization_report.md'
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(report_content)
    
    print(f"\n✓ 详细报告已保存至：{output_file}")
    return report_content


def main():
    """主函数"""
    print("\n" + "="*60)
    print("🤖 AI 自动优化 - 删除冗余代码")
    print("="*60)
    print(f"开始时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("工作目录：" + os.getcwd())
    
    # 确认操作
    print("\n⚠️  警告：此操作将修改您的文件")
    print("   建议先运行 Git 提交或备份重要文件\n")
    
    confirm = input("是否继续？(y/N): ")
    if confirm.lower() != 'y':
        print("✓ 操作已取消")
        return
    
    # 初始化统计
    stats = {
        'backup_deleted': 0,
        'backup_saved': 0,
        'html_optimized': 0,
        'html_saved': 0,
        'imports_removed': 0,
    }
    
    # 执行优化
    try:
        # 步骤 1: 删除备份文件
        backup_deleted, backup_saved = delete_backup_files()
        stats['backup_deleted'] = backup_deleted
        stats['backup_saved'] = backup_saved
        
        # 步骤 2: 优化 HTML 文件
        html_optimized, html_saved = batch_optimize_html_files()
        stats['html_optimized'] = html_optimized
        stats['html_saved'] = html_saved
        
        # 步骤 3: 删除未使用的导入
        _, imports_count = batch_remove_unused_imports()
        stats['imports_removed'] = imports_count
        
        # 生成报告
        print("\n" + "="*60)
        print("📝 生成最终报告")
        print("="*60)
        generate_final_report(stats)
        
        # 总结
        print("\n" + "="*60)
        print("🎉 优化完成！")
        print("="*60)
        total_saved = stats['backup_saved'] + stats['html_saved']
        print(f"总计节省空间：{total_saved:,} bytes")
        print(f"结束时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print("="*60 + "\n")
        
    except KeyboardInterrupt:
        print("\n\n✗ 操作被用户中断")
        sys.exit(1)
    except Exception as e:
        print(f"\n✗ 发生错误：{e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == '__main__':
    main()
