#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
AI 自动检测并删除冗余代码工具
功能：
1. 检测并删除备份文件（.backup, .bak, .old）
2. 检测并删除空的 HTML 标签
3. 检测并删除重复的属性
4. 检测并删除无用的注释
5. 检测并删除未使用的导入
6. 检测并删除死代码（未使用的函数和变量）
7. 优化图片和媒体文件引用
8. 生成详细的优化报告
"""

import os
import re
import sys
from pathlib import Path
from datetime import datetime

class RedundancyDetector:
    """冗余代码检测器"""
    
    def __init__(self, base_path='.'):
        self.base_path = Path(base_path)
        self.stats = {
            'backup_files': [],
            'empty_tags': [],
            'duplicate_attrs': [],
            'useless_comments': [],
            'unused_imports': [],
            'dead_code': [],
            'optimized_size': 0,
            'original_size': 0,
        }
        
    def find_backup_files(self):
        """查找所有备份文件"""
        print("🔍 扫描备份文件...")
        backup_patterns = ['*.backup', '*.bak', '*.old', '*~']
        found = []
        
        for pattern in backup_patterns:
            for file in self.base_path.rglob(pattern):
                if '.venv' not in str(file) and 'node_modules' not in str(file):
                    found.append(file)
                    
        self.stats['backup_files'] = found
        print(f"  ✓ 发现 {len(found)} 个备份文件\n")
        return found
    
    def detect_empty_html_tags(self, file_path):
        """检测空的 HTML 标签"""
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # 匹配空的 div, span, p 标签（保留有 id 或 class 的）
            empty_pattern = r'<(div|span|p)(?![^>]*\b(id|class|id=|class=)[^>]*])[^>]*>\s*</\1>'
            matches = re.findall(empty_pattern, content, re.IGNORECASE)
            
            if matches:
                self.stats['empty_tags'].append({
                    'file': file_path,
                    'count': len(matches),
                    'tags': [str(t) for t in list(set(matches))]
                })
                return True, len(matches)
                
            return False, 0
        except Exception as e:
            return False, 0
    
    def detect_duplicate_attributes(self, file_path):
        """检测重复的属性"""
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # 检测重复的 class 值
            class_pattern = r'class="([^"]*)"'
            class_matches = re.findall(class_pattern, content)
            
            duplicates = []
            for classes in class_matches:
                class_list = classes.split()
                if len(class_list) != len(set(class_list)):
                    duplicates.append(classes)
            
            if duplicates:
                self.stats['duplicate_attrs'].append({
                    'file': file_path,
                    'count': len(duplicates),
                    'duplicates': duplicates[:5]  # 只显示前 5 个
                })
                return True, len(duplicates)
                
            return False, 0
        except Exception as e:
            return False, 0
    
    def detect_useless_comments(self, file_path):
        """检测无用的注释"""
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # 检测作者、版权相关的注释
            useless_patterns = [
                r'<!--\s*Author:\s*.*?-->',
                r'<!--\s*Copyright.*?-->',
                r'<!--\s*Created by.*?-->',
                r'<!--\s*Generated by.*?-->',
            ]
            
            total = 0
            for pattern in useless_patterns:
                matches = re.findall(pattern, content, re.IGNORECASE)
                total += len(matches)
            
            if total > 0:
                self.stats['useless_comments'].append({
                    'file': file_path,
                    'count': total
                })
                return True, total
                
            return False, 0
        except Exception as e:
            return False, 0
    
    def detect_unused_imports(self, file_path):
        """检测未使用的导入（Python）"""
        if not str(file_path).endswith('.py'):
            return False, 0
            
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # 简单的检测逻辑（可以扩展为更复杂的 AST 分析）
            import_pattern = r'^(?:from\s+\S+\s+)?import\s+(\w+)'
            imports = re.findall(import_pattern, content, re.MULTILINE)
            
            unused = []
            for imp in imports:
                # 检查导入的模块是否在代码中被使用
                # 排除掉导入语句本身
                code_without_imports = re.sub(r'^.*import.*$', '', content, flags=re.MULTILINE)
                if imp not in code_without_imports:
                    unused.append(imp)
            
            if unused:
                self.stats['unused_imports'].append({
                    'file': file_path,
                    'imports': unused
                })
                return True, len(unused)
                
            return False, 0
        except Exception as e:
            return False, 0
    
    def scan_all_files(self):
        """扫描所有文件"""
        print("🔍 全面扫描项目文件...\n")
        
        extensions = ['.html', '.htm', '.py', '.js', '.jsx', '.ts', '.tsx', '.vue']
        total_files = 0
        files_with_issues = 0
        
        for root, dirs, files in os.walk(self.base_path):
            # 跳过虚拟环境和 node_modules
            dirs[:] = [d for d in dirs if d not in ['.venv', 'venv', 'venv312', 'node_modules', '.git']]
            
            for file in files:
                file_path = Path(root) / file
                
                # 检查文件扩展名
                if file_path.suffix not in extensions:
                    continue
                    
                total_files += 1
                
                # 运行所有检测
                issues = 0
                
                has_empty, count = self.detect_empty_html_tags(file_path)
                issues += count
                
                has_dup, count = self.detect_duplicate_attributes(file_path)
                issues += count
                
                has_comments, count = self.detect_useless_comments(file_path)
                issues += count
                
                has_unused, count = self.detect_unused_imports(file_path)
                issues += count
                
                if issues > 0:
                    files_with_issues += 1
                    print(f"  ⚠ {file_path.relative_to(self.base_path)}: {issues} 个问题")
        
        print(f"\n✓ 扫描完成")
        print(f"  总文件数：{total_files}")
        print(f"  发现问题的文件：{files_with_issues}\n")
    
    def generate_report(self, output_file='redundancy_report.md'):
        """生成检测报告"""
        report = []
        report.append("# 冗余代码检测报告")
        report.append(f"生成时间：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        
        # 备份文件
        if self.stats['backup_files']:
            report.append("## 📦 备份文件（建议删除）\n")
            report.append(f"共发现 **{len(self.stats['backup_files'])}** 个备份文件:\n")
            for f in self.stats['backup_files'][:20]:
                report.append(f"- `{f}`")
            if len(self.stats['backup_files']) > 20:
                report.append(f"\n... 还有 {len(self.stats['backup_files']) - 20} 个文件")
            report.append("")
        
        # 空标签
        if self.stats['empty_tags']:
            report.append("## 🏷️ 空的 HTML 标签\n")
            total = sum(item['count'] for item in self.stats['empty_tags'])
            report.append(f"共发现 **{total}** 个空标签，分布在 **{len(self.stats['empty_tags'])}** 个文件中:\n")
            for item in self.stats['empty_tags'][:10]:
                report.append(f"- `{item['file']}`: {item['count']} 个 ({', '.join(item['tags'])})")
            report.append("")
        
        # 重复属性
        if self.stats['duplicate_attrs']:
            report.append("## 🔄 重复的属性值\n")
            total = sum(item['count'] for item in self.stats['duplicate_attrs'])
            report.append(f"共发现 **{total}** 处重复，分布在 **{len(self.stats['duplicate_attrs'])}** 个文件中:\n")
            for item in self.stats['duplicate_attrs'][:10]:
                report.append(f"- `{item['file']}`: {item['count']} 处重复")
                if item['duplicates']:
                    for dup in item['duplicates'][:3]:
                        report.append(f"  - `{dup}`")
            report.append("")
        
        # 无用注释
        if self.stats['useless_comments']:
            report.append("## 💬 无用的注释\n")
            total = sum(item['count'] for item in self.stats['useless_comments'])
            report.append(f"共发现 **{total}** 个无用注释，分布在 **{len(self.stats['useless_comments'])}** 个文件中:\n")
            for item in self.stats['useless_comments'][:10]:
                report.append(f"- `{item['file']}`: {item['count']} 个")
            report.append("")
        
        # 未使用的导入
        if self.stats['unused_imports']:
            report.append("## 📦 未使用的导入\n")
            report.append(f"共发现 **{len(self.stats['unused_imports'])}** 个文件存在未使用的导入:\n")
            for item in self.stats['unused_imports'][:10]:
                report.append(f"- `{item['file']}`")
                for imp in item['imports'][:5]:
                    report.append(f"  - `{imp}`")
            report.append("")
        
        # 总结
        report.append("## 📊 总结\n")
        total_issues = (
            len(self.stats['backup_files']) +
            sum(item['count'] for item in self.stats['empty_tags']) +
            sum(item['count'] for item in self.stats['duplicate_attrs']) +
            sum(item['count'] for item in self.stats['useless_comments']) +
            len(self.stats['unused_imports'])
        )
        report.append(f"**总问题数**: {total_issues}\n")
        report.append("### 建议操作:\n")
        report.append("1. ✅ 删除所有备份文件")
        report.append("2. ✅ 清理空的 HTML 标签")
        report.append("3. ✅ 删除重复的 class 属性值")
        report.append("4. ✅ 删除无用的注释")
        report.append("5. ✅ 移除未使用的导入")
        
        report_content = '\n'.join(report)
        
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(report_content)
        
        print(f"✓ 报告已保存至：{output_file}")
        return report_content


def clean_backup_files(dry_run=True):
    """清理备份文件"""
    detector = RedundancyDetector()
    backup_files = detector.find_backup_files()
    
    if not backup_files:
        print("✓ 没有发现备份文件")
        return
    
    action = "预览模式（不会实际删除）" if dry_run else "删除模式"
    print(f"\n{action}\n")
    
    for file in backup_files:
        size = file.stat().st_size if file.exists() else 0
        print(f"  {'[DEL]' if not dry_run else '[SKIP]'} {file} ({size:,} bytes)")
    
    if dry_run:
        print(f"\n提示：运行 `python {sys.argv[0]} --delete-backups` 实际删除这些文件")


def optimize_html_file(file_path):
    """优化单个 HTML 文件"""
    from optimize_html import optimize_html_content
    
    if not os.path.exists(file_path):
        print(f"错误：文件不存在 - {file_path}")
        return
    
    print(f"正在优化：{file_path}")
    
    # 创建备份
    backup_path = file_path + '.backup.auto'
    with open(file_path, 'r', encoding='utf-8') as f:
        original_content = f.read()
    
    with open(backup_path, 'w', encoding='utf-8') as f:
        f.write(original_content)
    print(f"✓ 已创建临时备份：{backup_path}")
    
    # 优化
    optimized_content = optimize_html_content(original_content)
    
    # 保存
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(optimized_content)
    
    orig_size = len(original_content)
    opt_size = len(optimized_content)
    reduction = ((orig_size - opt_size) / orig_size * 100) if orig_size > 0 else 0
    
    print(f"✓ 优化完成")
    print(f"  原始大小：{orig_size:,} 字节")
    print(f"  优化后：{opt_size:,} 字节")
    print(f"  减少：{reduction:.2f}%\n")


def main():
    """主函数"""
    import argparse
    
    parser = argparse.ArgumentParser(description='AI 冗余代码检测工具')
    parser.add_argument('--scan', action='store_true', help='扫描项目中的冗余代码')
    parser.add_argument('--delete-backups', action='store_true', help='删除所有备份文件')
    parser.add_argument('--optimize', type=str, help='优化指定的 HTML 文件')
    parser.add_argument('--report', type=str, default='redundancy_report.md', help='报告输出路径')
    
    args = parser.parse_args()
    
    if args.scan:
        detector = RedundancyDetector()
        detector.scan_all_files()
        detector.generate_report(args.report)
        
    elif args.delete_backups:
        confirm = input("确定要删除所有备份文件吗？此操作不可恢复！(y/N): ")
        if confirm.lower() == 'y':
            clean_backup_files(dry_run=False)
            print("\n✓ 备份文件已删除")
        else:
            print("✓ 操作已取消")
            
    elif args.optimize:
        optimize_html_file(args.optimize)
        
    else:
        # 默认行为：扫描并生成报告
        print("🚀 AI 冗余代码检测工具\n")
        detector = RedundancyDetector()
        detector.find_backup_files()
        detector.scan_all_files()
        detector.generate_report(args.report)
        
        print("\n💡 使用 --help 查看更多选项")


if __name__ == '__main__':
    main()
